apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-ai-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-ai
  template:
    metadata:
      labels:
        app: devops-ai
    spec:
      containers:
        - name: devops-ai
          image: your-dockerhub-username/ai-devops-ai:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
